version: '2'
services:
  ais:
    build: ./ais
    image: ais
    restart: unless-stopped
    environment:
      - LAT=
      - LON=
      - AIS_STATION_NAME=
      - AIS_DEVICE=00000162
      - AIS_FEED_LOCALHOST="127.0.0.1:10110"
    devices:
      - "/dev/bus/usb"
    expose:
      - "8100"
      - "10110"
    ports:
      - "8100:8100"
      - "10110:10110"
