version: '2'
services:
  ais:
    build: ./ais
    image: ais
    restart: unless-stopped
    environment:
      - LAT=
      - LON=
      - AIS_STATION_NAME=
      - AIS_DEVICE=0
      - AIS_WEB_PORT=8100 
    devices:
      - "/dev/bus/usb"
    expose:
      - "8100"
      - "10110"
    ports:
      - "8100:8100"
      - "10110:10110"
