version: '2'
services:
  ais:
    build: ./ais
    image: ais
    restart: unless-stopped
    environment:
      - LAT=
      - LON=
      - AIS_STATION_NAME=
      - AIS_DEVICE=0
      - AIS_TUNER_BANDWIDTH=192K
      - AIS_DEVICE_CORRECTION_PPM=0
      - AIS_OUTPUT_MODE=0
      - AIS_VERBOSE_MODE=30
      - AIS_ADDITIONAL_METADATA=DTM
      - AIS_WEB_PORT=8100
    devices:
      - "/dev/bus/usb"
    expose:
      - "8100"
    ports:
      - "8100:8100"
    labels:
      io.balena.features.supervisor-api: '1'
